ai_context_version: 1.0

# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

project:
  name: heimlern
  summary: Reinforcement-/Bandit-Policy-Framework (Rust)
  role: policy_engine
  primary_language: rust
  visibility: internal

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - policies
        - validation_schemas
    - name: heimlern
      relationship: uses
      interface:
        - quality_scores
  external:
    - name: ajv-cli

architecture:
  entrypoints:
    - crates/heimlern-bandits/examples/decide.rs
    - crates/heimlern-bandits/src/lib.rs

conventions:
  branching: "main, feature/*"
  commit_prefix: "sichter"
  ci_platform: github_actions

documentation:
  runbook: docs/runbook.md

ai_guidance:
  do:
    - prefer warnings unless contracts are violated
  dont:
    - block on stylistic concerns without policy basis
